# Generated by Django 4.1.7 on 2023-03-26 21:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_data',
            fields=[
                ('USER_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_USER_ID', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Speciality', models.CharField(max_length=500)),
                ('Experience', models.IntegerField()),
                ('PHONENUMBER', models.CharField(blank=True, help_text='Enter Number in format: "9999999999"', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with '9999999999'", regex='^[7-9]{1}\\d{9}')])),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_plan_data',
            fields=[
                ('Insurance_plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Plan_name', models.CharField(max_length=200)),
                ('Plan_description', models.CharField(max_length=1000)),
                ('Monthly_premium', models.IntegerField()),
                ('Coverage_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Provider_data',
            fields=[
                ('USER_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Insurance_USER_ID', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('PHONENUMBER', models.CharField(blank=True, help_text='Enter Number in format: "9999999999"', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with '9999999999'", regex='^[7-9]{1}\\d{9}')])),
            ],
        ),
        migrations.CreateModel(
            name='Symptom_Specialities_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom_Name', models.CharField(max_length=500)),
                ('Speciality', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_data',
            fields=[
                ('USER_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_USER_ID', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Date_of_Birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('PHONENUMBER', models.CharField(blank=True, help_text='Enter Number in format: "9999999999"', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must start with '9999999999'", regex='^[7-9]{1}\\d{9}')])),
                ('is_covid', models.BooleanField()),
                ('Date_of_Admission', models.DateField()),
                ('Date_of_Discharge', models.DateField()),
                ('Room_number', models.IntegerField()),
                ('bed_number', models.IntegerField()),
                ('Doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Doctor_id', to='allinone.doctor_data')),
                ('Insurance_plan_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Insurance_plan_id', to='allinone.insurance_plan_data')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_history_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_visit', models.DateField(unique=True)),
                ('Diagnosis', models.CharField(max_length=500)),
                ('Treatment', models.CharField(max_length=500)),
                ('Nodes', models.CharField(max_length=1000)),
                ('Doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Medical_history_Doctor_id', to='allinone.doctor_data')),
                ('Patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Medical_history_Patient_id', to='allinone.patient_data')),
            ],
        ),
        migrations.AddField(
            model_name='insurance_plan_data',
            name='Provider_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Insurance_Provider_id', to='allinone.insurance_provider_data'),
        ),
        migrations.CreateModel(
            name='Appointmnet_data',
            fields=[
                ('Appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Appointmnet_Date', models.DateField()),
                ('Appointmnet_Time', models.DateTimeField()),
                ('Symptons', models.CharField(max_length=500)),
                ('Nodes', models.CharField(max_length=1000)),
                ('Doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Appointmnet_Doctor_id', to='allinone.doctor_data')),
                ('Patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Appointmnet_Patient_id', to='allinone.patient_data')),
            ],
        ),
    ]
